name: Build and Deploy Docs

on:
  push:
    branches: [ docs ]
    paths:
      - 'Src/**'
      - 'doc_project/**'
      - '.github/workflows/build-docs.yml'

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Install DocFX
        run: dotnet tool update -g docfx
      - name: Clean previous output
        run: |
          rm -rf doc_project/api
          rm -rf docs

      - name: Build DocFX site
        working-directory: ./doc_project
        run: |
          docfx metadata
          docfx build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages
