<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<AllowBuild>true</AllowBuild>
		<!-- required to silence VS -->
		<OutputType>Library</OutputType>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<ProduceReferenceAssembly>false</ProduceReferenceAssembly>
		<BuildProjectReferences>false</BuildProjectReferences>
		<SkipCompilerExecution>true</SkipCompilerExecution>
		<!-- THIS is the magic -->
		<EmitCompilerGeneratedFiles>false</EmitCompilerGeneratedFiles>
		<CopyBuildOutputToOutputDirectory>false</CopyBuildOutputToOutputDirectory>
		<RunPostBuildEvent>Never</RunPostBuildEvent>
	</PropertyGroup>


	<Target Name="CleanDocfxOutput" AfterTargets="Clean">
		<RemoveDir Directories="$(MSBuildProjectDirectory)\..\docs" />
		<!--<RemoveDir Directories="$(MSBuildProjectDirectory)\docs" />-->
		<RemoveDir Directories="$(MSBuildProjectDirectory)\api" />
	</Target>

	<Target Name="BuildDocfx" AfterTargets="Build">
		<!--Automatically run docPreBuild_ python scripts to prep md files for docfx.-->
		<ItemGroup>
			<DocPreBuildScripts Include="**\docPreBuild_*.py" />
		</ItemGroup>
		<Message Text="Running docPreBuild_*.py scripts..." />
		<Exec Command="@(DocPreBuildScripts->'python &quot;%(FullPath)&quot;', ' &amp;&amp; ')" />
		
		<!--Build DocFX-->
		<Message Text="Building DocFX documentation..." Importance="high" />
		<Exec Command="docfx metadata docfx.json" WorkingDirectory="$(MSBuildProjectDirectory)" />

		<!--Automatically run docMidBuild_ python scripts to prep md files for docfx.-->
		<ItemGroup>
			<DocMidBuildScripts Include="**\docMidBuild_*.py" />
		</ItemGroup>
		<Message Text="Running docMidBuild_*.py scripts..." />
		<Exec Command="@(DocMidBuildScripts->'python &quot;%(FullPath)&quot;', ' &amp;&amp; ')" />
		
		
		<Exec Command="docfx build docfx.json" WorkingDirectory="$(MSBuildProjectDirectory)" />
	</Target>
</Project>
